from typing import Protocol
from .contracts import ApprovalPage, ApprovalSnapshot

class ApprovalRepository(Protocol):
    def get(self, identifier: str, tenant_id: str) -> ApprovalSnapshot | None: ...
    def list_for_tenant(self, tenant_id: str, cursor: str | None = None, limit: int = 50) -> ApprovalPage: ...
